### ISSUE TITLE
DAPLink of the LPC2148 missing

### ISSUE THREAD

**Issue by joelvonrotz** [ARMmbed/mbed-HDK#12]
I have noticed, that the current interface chip the LPC2148 used on the mbed LPC1768 isn't included in the HDK. Why isn't it in the HDK?

EDIT:
Oh, I found something on the forum:
https://os.mbed.com/questions/76861/mbed-IF01/
So it's more for keeping it a secret. But isn't it possible to possible to provide a compiled file to directly program it onto the LPC2148?

**Comment by andcor02** [comment]
Hi,

Yes for the exact reason you mentioned it cannot be disclosed, nor the interface firmware.

**Comment by joelvonrotz** [comment]
Oh all right, thank you for the response!
